### ISSUE TITLE
Linux shortcut keys

### ISSUE THREAD

**Issue by kamil-karkus** [hjnilsson/rme#10]
Shortcut keys won't work.

**Comment by diath** [comment]
Anyone had any luck with this? The only relevant note I've found about the issue was this:
https://www.wxwidgets.org/docs/faq/windows/#shortcutproblem

Even though it's a Windows FAQ, I guess the same thing could be true for Windows, although I went through a few classes and they seem to call event.Skip() properly. Not sure about the menus though, I'm not really familiar with wxWidgets.
