### ISSUE TITLE
Change tile z-order

### ISSUE THREAD

**Issue by iespadim** [hjnilsson/rme#162]
this adds the possibility of changing wich border is going to be displayed on the intersection of two distinct brushes.

currently to do so I use 2 data folders to make it happen.

how hard is to do that? i dont know how to do it, neither where to fuck with it to make it happen

**Comment by hjnilsson** [comment]
You can control the z-order of brushes already in the data files of the editor. Is it something else you are referring to?

**Comment by EpicIcaro** [comment]
this is the current way that grounds are put on the map editor: the jungle grass is always above the darker grass, because the brush z-order is higher. But what happens if i want to the darker grass' border to be higher than the jungle's? i have to edit on data or extensions:
![0](https://cloud.githubusercontent.com/assets/3754764/20981183/b5f15794-bc9a-11e6-8163-c97e0c5d1147.PNG)

isn't it hard to make a context menu like this: that would prompt you a text box that user will put the desired z- level of a brush, so the next time user uses a brush, the z-level will be higher and so the borders will hange priority
![1](https://cloud.githubusercontent.com/assets/3754764/20981185/b61262e0-bc9a-11e6-9aef-085047d555f1.PNG)

the next time user use the brush, the result will be like that
![3](https://cloud.githubusercontent.com/assets/3754764/20981186/b62b728a-bc9a-11e6-9381-d7ed4337b5b0.PNG)


i have trouble explaining things.

**Comment by Kamenuvol** [comment]
I understood what you want, is like editing outer xml inside the program. I like it, It should be possible for every xml of extensions
