### ISSUE TITLE
where i can find a list that shows what are the xml attributes that i can use on grounds, borders etc?

### ISSUE THREAD

**Issue by iespadim** [hjnilsson/rme#183]
i'm trying to get my grounds.xml near perfect for autoborder because i find very annoying to put things mannually.

also i want to know if its possible to offset optional border to use it alongside with outer borders

**Comment by hjnilsson** [comment]
What do you mean by offset optional border?

Unfortunately the attributes are not documented. Your best ability is to just look at the grounds.xml file: https://github.com/hjnilsson/rme/blob/master/data/854/grounds.xml

and compare to the code here: https://github.com/hjnilsson/rme/blob/master/source/ground_brush.cpp#L133

**Comment by EpicIcaro** [comment]
i have this basalt mountain:
![image](https://cloud.githubusercontent.com/assets/3754764/24077372/ed9ea2e4-0c29-11e7-903c-d575f14920d3.png)

with the border, the basalt mountain will look like this:
![image](https://cloud.githubusercontent.com/assets/3754764/24077375/111aaa7e-0c2a-11e7-8727-62b381375ba9.png)

the problem is that the border is not complete, it's missing the border's continuation, at the end looking like this:
![image](https://cloud.githubusercontent.com/assets/3754764/24077379/5b00f1b6-0c2a-11e7-98b9-7fc55cf68383.png)

so, the border of the border should have a offset of 1sqm from the brush

hope you understand

**Comment by EpicIcaro** [comment]
that's not possible?

**Comment by EpicIcaro** [comment]
Trying to explain better:

first creating borders for this tile:
![222](https://cloud.githubusercontent.com/assets/3754764/25245843/3629b762-25dc-11e7-8347-f79b9c051d99.PNG)

<brush name="basalt" type="ground" server_lookid="17854" z-order="19900">
<item id="17854" chance="2500"/>
<item id="17855" chance="2000"/>
<item id="17856" chance="2500"/>
<item id="17857" chance="2500"/>

<friend name="purple crystal mountain"/>
</brush>


then i add border to "none"

![333](https://cloud.githubusercontent.com/assets/3754764/25245863/469ff624-25dc-11e7-903d-9c53f6b77b49.PNG)

<brush name="basalt" type="ground" server_lookid="17854" z-order="19900">
<item id="17854" chance="2500"/>
<item id="17855" chance="2000"/>
<item id="17856" chance="2500"/>
<item id="17857" chance="2500"/> 

<border align="outer" to="none" id="7778"/>

<friend name="purple crystal mountain"/>
</brush>


Then I decided to put the mountain wall:

![4444](https://cloud.githubusercontent.com/assets/3754764/25245867/4cb846b0-25dc-11e7-85ac-9f4fa54c8bad.PNG)

<brush name="basalt" type="ground" server_lookid="17854" z-order="19900">
<item id="17854" chance="2500"/>
<item id="17855" chance="2000"/>
<item id="17856" chance="2500"/>
<item id="17857" chance="2500"/> 

<border align="outer" to="none" id="7778"/>
<border align="outer" id="61"/>

<friend name="purple crystal mountain"/>
</brush>


In the next step, I would like to add the edges as seen in the following image, but in theory they appear below the current walls and so they do not appear on the map. Or is this because the editor does not use two edges with the same "align" at the same time?

![111111](https://cloud.githubusercontent.com/assets/3754764/25245886/59a64142-25dc-11e7-8e4a-73b81f458b30.PNG)


If I add the walls as align = "inner" and invert the walls, they come out as in the figure below.

![555](https://cloud.githubusercontent.com/assets/3754764/25245891/5ef7b4e6-25dc-11e7-94d9-d146f2d4e20d.PNG)


Briefly explaining the problem: I need to put two "outer" edges, but one must be "outer outer", ie, offset 1sqm more than the outer edge.
Is there any way to do the auto border correctly as in the penultimate image? (not by hand heh)
